services:
  api:
    build:
      context: ./backend-flask
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    networks:
      - lang-portal-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:8000
    networks:
      - lang-portal-network

  importer:
    build:
      context: ./lang-importer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

networks:
  lang-portal-network:
    driver: bridge